namespace: "shokxi"
name: "example_collection"
version: "1.0.0"
description: "Various pieces of content"
authors:
  - "Jake Jackson <jljacks93@gmail.com>"
license:
  - "GPL-3.0"
repository: "https://www.github.com/thedoubl3j/my_collection"
readme: README.md
tags: []
dependencies: {}
